<?php
/* Generated by SimpleLocalize on 2023-10-27T12:02:38.641476125Z */

return [
    "alert" => "We openen het restaurant op de eerste dag van november.",
    "group" => "Groepen",
    "status" => "We zijn vandaag open",
];
?>
