<?php
/* Generated by SimpleLocalize on 2023-10-27T12:20:07.699442542Z */

return [
    "contacteer" => "Contact us",
    "doorlopend openn" => "continuously open",
    "geopend alle dagen" => "The View Antwerp is open all days from 11:00 to 00:00.",
    "ligging" => "Location",
    "nieuwsbrief" => "Newsletter",
    "openingsuren" => "Opening hours",
    "openingsuren keuken" => "kitchen opening hours",
    "reserveer" => "Book",
    "schrijf" => "Subscribe to our newsletter and stay informed!",
];
?>
