<?php
/* Generated by SimpleLocalize on 2023-10-27T12:02:38.641328224Z */

return [
    "alert" => "Nous ouvrirons le restaurant le premier jour de novembre.",
    "group" => "Groupes",
    "status" => "Nous sommes ouverts aujourd'hui",
];
?>
