<?php
/* Generated by SimpleLocalize on 2023-10-27T12:02:38.641240713Z */

return [
    "alert" => "Abriremos el restaurante el primer día de noviembre.",
    "group" => "Grupos",
    "status" => "Hoy estamos abiertos",
];
?>
